//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Applabs_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
        public string Passport_Number { get; set; }
        public bool Idproof { get; set; }
        public string Contact_Number { get; set; }
        public string Permanent_Address { get; set; }
        public string Blood_Group { get; set; }
        public string Qualification { get; set; }
        public string Technology { get; set; }
        public bool Is_Internal_Employee { get; set; }
    }
}
