//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Applabs_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marketing
    {
        public int Id { get; set; }
        public string Employee_Name { get; set; }
        public string Marketer_name { get; set; }
        public System.DateTime Start_date { get; set; }
        public string case_status { get; set; }
        public Nullable<System.DateTime> Close_date { get; set; }
    }
}
